import type { SceneGroup } from "../SceneBase";

export const smg1SceneGroup: SceneGroup = {
	id: "smg",
	name: "Super Mario Galaxy",
	sceneDescs: [
		"Observatory",
		{ name: "Comet Observatory", id: "AstroGalaxy" },
		{ name: "Library", id: "LibraryRoom" },
		{ name: "Peach's Castle Gardens", id: "PeachCastleGardenGalaxy" },
		{ name: "Gateway Galaxy", id: "HeavensDoorGalaxy" },
		{ name: "Boo's Boneyard Galaxy", id: "TeresaMario2DGalaxy" },
		"Terrace",
		{ name: "Terrace", id: "AstroDome0" },
		{ name: "Good Egg Galaxy", id: "EggStarGalaxy" },
		{ name: "Honeyhive Galaxy", id: "HoneyBeeKingdomGalaxy" },
		{ name: "Loopdeeloop Galaxy", id: "SurfingLv1Galaxy" },
		{ name: "Flipswitch Galaxy", id: "FlipPanelExGalaxy" },
		{ name: "Sweet Sweet Galaxy", id: "BeltConveyerExGalaxy" },
		{ name: "Bowser Jr.'s Robot Reactor", id: "TriLegLv1Galaxy" },
		"Fountain",
		{ name: "Fountain", id: "AstroDome1" },
		{ name: "Space Junk Galaxy", id: "StarDustGalaxy" },
		{ name: "Battlerock Galaxy", id: "BattleShipGalaxy" },
		{ name: "Rolling Green Galaxy", id: "TamakoroExLv1Galaxy" },
		{ name: "Hurry-Scurry Galaxy", id: "BreakDownPlanetGalaxy" },
		{ name: "Sling Pod Galaxy", id: "CocoonExGalaxy" },
		{ name: "Bowser's Star Reactor", id: "KoopaBattleVs1Galaxy" },
		"Kitchen",
		{ name: "Kitchen", id: "AstroDome2" },
		{ name: "Beach Bowl Galaxy", id: "HeavenlyBeachGalaxy" },
		{ name: "Ghostly Galaxy", id: "PhantomGalaxy" },
		{ name: "Bubble Breeze Galaxy", id: "CubeBubbleExLv1Galaxy" },
		{ name: "Buoy Base Galaxy", id: "OceanFloaterLandGalaxy" },
		{ name: "Drip Drop Galaxy", id: "TearDropGalaxy" },
		{ name: "Bowser Jr.'s Airship Armada", id: "KoopaJrShipLv1Galaxy" },
		"Bedroom",
		{ name: "Bedroom", id: "AstroDome3" },
		{ name: "Gusty Garden Galaxy", id: "CosmosGardenGalaxy" },
		{ name: "Freezeflame Galaxy", id: "IceVolcanoGalaxy" },
		{ name: "Dusty Dune Galaxy", id: "SandClockGalaxy" },
		{ name: "Honeyclimb Galaxy", id: "HoneyBeeExGalaxy" },
		{ name: "Bigmouth Galaxy", id: "FishTunnelGalaxy" },
		{ name: "Bowser's Dark Matter Plant", id: "KoopaBattleVs2Galaxy" },
		"Engine Room",
		{ name: "Engine Room", id: "AstroDome4" },
		{ name: "Gold Leaf Galaxy", id: "ReverseKingdomGalaxy" },
		{ name: "Sea Slide Galaxy", id: "OceanRingGalaxy" },
		{ name: "Toy Time Galaxy", id: "FactoryGalaxy" },
		{ name: "Bonefin Galaxy", id: "SkullSharkGalaxy" },
		{ name: "Sand Spiral Galaxy", id: "TransformationExGalaxy" },
		{ name: "Bowser Jr.'s Lava Reactor", id: "FloaterOtaKingGalaxy" },
		"Garden",
		{ name: "Garden", id: "AstroDome5" },
		{ name: "Deep Dark Galaxy", id: "OceanPhantomCaveGalaxy" },
		{ name: "Dreadnought Galaxy", id: "CannonFleetGalaxy" },
		{ name: "Melty Molten Galaxy", id: "HellProminenceGalaxy" },
		{ name: "Matter Splatter Galaxy", id: "DarkRoomGalaxy" },
		{ name: "Snow Cap Galaxy", id: "SnowCapsuleGalaxy" },
		"Center of the Universe",
		{ name: "Bowser's Galaxy Reactor", id: "KoopaBattleVs3Galaxy" },
		"Planet of Trials",
		{ name: "Rolling Gizmo Galaxy", id: "TamakoroExLv2Galaxy" },
		{ name: "Bubble Blast Galaxy", id: "CubeBubbleExLv2Galaxy" },
		{ name: "Loopdeeswoop Galaxy", id: "SurfingLv2Galaxy" },
		{ name: "Grand Finale Galaxy", id: "PeachCastleFinalGalaxy" },
		"?",
		{ name: "Day in the Life of a Luma", id: "DayInTheLifeOfALuma" },
	],
	async createScene(...args) {
		const { createScene } = await import('./Scenes_SuperMarioGalaxy1');
		return await createScene(...args);
	}
};

export const smg2SceneGroup: SceneGroup = {
	id: "smg2",
	name: "Super Mario Galaxy 2",
	sceneDescs: [
		"Other Maps",
		{ name: "Mushroom Kingdom", id: "PeachCastleGalaxy" },
		{ name: "Mario's Faceship", id: "MarioFaceShipGalaxy" },
		{ name: "Credits", id: "StaffRollGalaxy" },
		{ name: "Library", id: "ChildRoomGalaxy" },
		"World One",
		{ name: "World One Map", id: "WorldMap01Galaxy" },
		{ name: "Sky Station Galaxy", id: "IslandFleetGalaxy" },
		{ name: "Yoshi Star Galaxy", id: "YosshiHomeGalaxy" },
		{ name: "Spin-Dig Galaxy", id: "DigMineGalaxy" },
		{ name: "Fluffy Bluff Galaxy", id: "MokumokuValleyGalaxy" },
		{ name: "Flip-Swap Galaxy", id: "RedBlueExGalaxy" },
		{ name: "Rightside-Down Galaxy", id: "AbekobeGalaxy" },
		{ name: "Bowser Jr.'s Fiery Flotilla", id: "VsKoopaJrLv1Galaxy" },
		"World Two",
		{ name: "World Two Map", id: "WorldMap02Galaxy" },
		{ name: "Puzzle Plank Galaxy", id: "HomeCenterGalaxy" },
		{ name: "Hightail Falls Galaxy", id: "BigWaterFallGalaxy" },
		{ name: "Boulder Bowl Galaxy", id: "GoroRockGalaxy" },
		{ name: "Cosmic Cove Galaxy", id: "StarCreekGalaxy" },
		{ name: "Wild Glide Galaxy", id: "JungleGliderGalaxy" },
		{ name: "Honeybloom Galaxy", id: "FlowerHighlandGalaxy" },
		{ name: "Bowser's Lava Lair", id: "VsKoopaLv1Galaxy" },
		"World Three",
		{ name: "World Three Map", id: "WorldMap03Galaxy" },
		{ name: "Tall Trunk Galaxy", id: "BigTree2Galaxy" },
		{ name: "Cloudy Court Galaxy", id: "CloudGardenGalaxy" },
		{ name: "Haunty Halls Galaxy", id: "GhostConveyorGalaxy" },
		{ name: "Freezy Flake Galaxy", id: "WhiteSnowGalaxy" },
		{ name: "Rolling Masterpiece Galaxy", id: "TamakoroPlanetGalaxy" },
		{ name: "Beat Block Galaxy", id: "TimerSwitchingPlatformGalaxy" },
		{ name: "Bowser Jr.'s Fearsome Fleet", id: "KoopaJrLv2Galaxy" },
		"World Four",
		{ name: "World Four Map", id: "WorldMap04Galaxy" },
		{ name: "Supermassive Galaxy", id: "BigGalaxy" },
		{ name: "Flipsville Galaxy", id: "OmoteuLandGalaxy" },
		{ name: "Starshine Beach Galaxy", id: "TropicalResortGalaxy" },
		{ name: "Chompworks Galaxy", id: "WanwanFactoryGalaxy" },
		{ name: "Sweet Mystery Galaxy", id: "MysteryCandyGalaxy" },
		{ name: "Honeyhop Galaxy", id: "HoneyBeeVillageGalaxy" },
		{ name: "Bowser's Gravity Gauntlet", id: "VsKoopaGravityGalaxy" },
		"World Five",
		{ name: "World Five Map", id: "WorldMap05Galaxy" },
		{ name: "Space Storm Galaxy", id: "ThunderFleetGalaxy" },
		{ name: "Slipsand Galaxy", id: "QuicksandGalaxy" },
		{ name: "Shiverburn Galaxy", id: "KachikochiLavaGalaxy" },
		{ name: "Boo Moon Galaxy", id: "TeresaLabyrinthGalaxy" },
		{ name: "Upside Dizzy Galaxy", id: "ChaosGravityGalaxy" },
		{ name: "Fleet Glide Galaxy", id: "ChallengeGliderGalaxy" },
		{ name: "Bowser Jr.'s Boom Bunker", id: "VsKoopaJrLv3Galaxy" },
		"World Six",
		{ name: "World Six Map", id: "WorldMap06Galaxy" },
		{ name: "Melty Monster Galaxy", id: "TwisterTowerGalaxy" },
		{ name: "Clockwork Ruins Galaxy", id: "AncientExcavationGalaxy" },
		{ name: "Throwback Galaxy", id: "LongForCastleGalaxy" },
		{ name: "Battle Belt Galaxy", id: "MagicGalaxy" },
		{ name: "Flash Black Galaxy", id: "MemoryRoadGalaxy" },
		{ name: "Slimy Spring Galaxy", id: "UnderGroundDangeonGalaxy" },
		{ name: "Bowser's Galaxy Generator", id: "VsKoopaLv3Galaxy" },
		"World S",
		{ name: "World S Map", id: "WorldMap07Galaxy" },
		{ name: "Mario Squared Galaxy", id: "MarioOnMarioGalaxy" },
		{ name: "Rolling Coaster Galaxy", id: "TamakoroSliderGalaxy" },
		{ name: "Twisty Trials Galaxy", id: "SecretAthleticGalaxy" },
		{ name: "Stone Cyclone Galaxy", id: "MadnessOnimasuGalaxy" },
		{ name: "Boss Blitz Galaxy", id: "KingOfKingsGalaxy" },
		{ name: "Flip-Out Galaxy", id: "SwitchMoveBlockGalaxy" },
		{ name: "Grandmaster Galaxy", id: "DimensionBigCastleGalaxy" },
	],
	async createScene(...args) {
		const { createScene } = await import('./Scenes_SuperMarioGalaxy2');
		return await createScene(...args);
	}
};
